version: '3'

services:
  mockdoc:
    image: h4ngar/mockdoc:latest
    container_name: mockdoc
    restart: unless-stopped
    environment:
      MONGO_SERVER: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: admin
      MONGO_USER: root
      MONGO_PASSWORD: mongo
