version: '3'

services:
  mockdoc:
    image: mockdoc:latest
    container_name: mockdoc
    restart: unless-stopped
    environment:
      MONGO_SERVER: ${MONGO_SERVER:?MONGO_SERVER must be set}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE:?MONGO_DATABASE must be set}
      MONGO_USER: ${MONGO_USER:?MONGO_USER must be set}
      MONGO_PASSWORD: ${MONGO_PASSWORD:?MONGO_PASSWORD must be set}
