import React, { useEffect, useState } from 'react';
import { Card, Col, Divider, message, Modal, Row, Typography, Radio } from 'antd';
import { Form, FormItem, Button } from '@react-hangar/antd-components';
import { useStore } from '@scripty/react-store';
import { charsetTypeOptions, contentTypeOptions, statusOptions } from './options';
import { getCategoryOptions, getMockServiceUrl } from '../helper'
import { useParams } from 'react-router';
import { Path } from './Path';
import { validate } from './validator';

export const NewMock = () => {
    const { mockStore } = useStore('mockStore');
    const { categoriesStore } = useStore('categoriesStore');
    const [visible, setVisible] = useState(false);
    const [method, setMethod] = useState('GET');
    const [disabled, setDisabled] = useState('none');
    const updated = mockStore.getUpdatedRecords();
    const categoriesRecords = categoriesStore.getRecords();
    const categoryOptions = getCategoryOptions(categoriesRecords[0].list);
    const { Text } = Typography;
    const records = mockStore.getRecords();
    const params = useParams();

    useEffect(() => {
        if (params) {
            const path = window.location.pathname.replace('/mock-edit/', '');
            const parameter = window.location.search;
            mockStore.getProxy().search({ query: path + parameter })
        }
    }, []);

    useEffect(() => {
        categoriesStore.getProxy().read({})
    }, []);

    const initialRecord = {
        title: '',
        category: '',
        requestHeaders: '',
        requestBody: '',
        requestPath: {
            path: '',
            isAutoGenerated: true
        },
        responseStatus: 200,
        responseContentType: 'application/json',
        responseCharset: 'UTF-8'
    }

    const update = async (form) => {
        try {
            await mockStore.getProxy().update({ ...form });
            setVisible(true);
        } catch (e) {
            message.error(e);
        }
    }

    const handleSubmit = async (data, form) => {
        let validatedForm = validate(form);
        if (typeof validatedForm === 'object') await update(validatedForm);
    };

    const onModalOkBtnClick = () => {
        setVisible(false);
    }

    const onModalCancelBtnClick = () => {
        setVisible(false);
    }
    const sizedContent = {
        xs: { span: 24, offset: 0 }, xl: { span: 18, offset: 3 }
    };

    const inlineStyled = {
        padding: 5, display: 'inline-block', width: 'calc(50%)'
    }

    const onMethodChange = (e) => {
      if (e.target.value === 'POST') {
          setDisabled('inline-block');
          return setMethod('POST');
      }
        setDisabled('none');
        setMethod('GET');
    };

    return (
        <Row>
            <Col {...sizedContent} >
                <Card title={'Design Mock'}>
                    <Form onSubmit={handleSubmit} record={(params && records.length === 1) ? records[0] : initialRecord}>
                        <FormItem fieldType={'string'} label='Title' dataIndex={'title'}
                                  style={inlineStyled}
                        />

                        <FormItem fieldType={'select'} label='Category' dataIndex={'category'}
                                  style={inlineStyled} fieldProps={{ options: categoryOptions }}/>

                        <Divider>Request</Divider>

                        <Radio.Group defaultValue="GET" value={method} onChange={onMethodChange}>
                            <Radio.Button value="GET">GET</Radio.Button>
                            <Radio.Button value="POST">POST</Radio.Button>
                        </Radio.Group>

                        <FormItem label='Request Path' dataIndex={'requestPath'}
                                  fieldProps={{placeholder: '/yourpath/api/?myparams=1234&awesome=5678'}}
                        >
                            <Path />
                        </FormItem>

                        <FormItem fieldType={'object'} label='Request Headers' dataIndex={'requestHeaders'} style={inlineStyled}/>

                        <FormItem fieldType={'object'} label='Request Body' dataIndex={'requestBody'} style={{ ...inlineStyled, display: disabled }} />

                        <Divider>Response</Divider>

                        <FormItem fieldType={'select'} label='HTTP Status' dataIndex={'responseStatus'}
                                  fieldProps={{options: statusOptions}} required style={inlineStyled}/><br />

                        <FormItem fieldType={'select'} label='ContentType' dataIndex={'responseContentType'}
                                  fieldProps={{ options: contentTypeOptions }} required style={inlineStyled}/>

                        <FormItem fieldType={'select'} label='Charset' dataIndex={'responseCharset'}
                                  fieldProps={{ options: charsetTypeOptions }} required style={inlineStyled}/>

                        <FormItem fieldType={'object'} label='Response Headers' dataIndex={'responseHeaders'} style={inlineStyled}/>

                        <FormItem fieldType={'object'} label='Response Body' dataIndex={'responseBody'} style={inlineStyled}/>

                        <Button htmlType="submit" icon={'save'}> Save </Button>

                        <Modal
                            title={'Mock is ready:'}
                            visible={visible}
                            width={600}
                            onOk={onModalOkBtnClick}
                            onCancel={onModalCancelBtnClick}
                            onClose={onModalCancelBtnClick}
                        >
                            <Text style={{ fontSize: 18 }} copyable code>
                                {getMockServiceUrl((updated && typeof updated.requestPath !== 'undefined') ? updated.requestPath.path : '')}
                            </Text>
                        </Modal>
                    </Form>
                </Card>
            </Col>
        </Row>
    );
};
