import React, { useState } from 'react';
import { Checkbox, Col, Input } from 'antd';
import Row from 'antd/es/grid/row';
import { nanoid } from 'nanoid';

export const Path = (props) => {

    const { onChange, value = {path: '', isAutoGenerated: true} } = props;
    const [ state, setState ] = useState({ isAutoGenerated: value.isAutoGenerated, path: value.path })

    const onCheckboxChange = (e) => {

        let path = (e.target.checked) ? nanoid() : state.path;

        setState({
            isAutoGenerated: e.target.checked,
            path
        });

        onChange(state)
    };

    const onInputChange = (e) => {
        setState({
            isAutoGenerated: state.isAutoGenerated,
            path: e.target.value
        });

        onChange(state)
    }

    return (
        <Row>
            <Col>
                <Input
                    value={state.path}
                    disabled={state.isAutoGenerated}
                    placeholder={'/yourpath/api/?myparams=1234&awesome=5678'}
                    onChange={onInputChange}
                />
            </Col>
            <Col>
                <Checkbox
                    checked={state.isAutoGenerated}
                    onChange={onCheckboxChange}
                >
                    Auto Generate
                </Checkbox>
            </Col>
        </Row>
    );
};

export const EditPath = (props) => {

    const { onChange, value = {path: '', isAutoGenerated: true} } = props;
    const [ state, setState ] = useState({ isAutoGenerated: value.isAutoGenerated, path: value.path })

    const onInputChange = (e) => {
        setState({
            isAutoGenerated: state.isAutoGenerated,
            path: e.target.value
        });

        onChange(state)
    }

    return (
        <Row>
            <Col>
                <Input
                    value={state.path}
                    placeholder={'/yourpath/api/?myparams=1234&awesome=5678'}
                    onChange={onInputChange}
                />
            </Col>
        </Row>
    );
};
