import { createStore } from '@scripty/react-store';

export default createStore({
    name: 'mockStore',
    model: {
        _id: null,
        responseStatus: 200,
        responseContentType: 'application/json',
        responseCharset: 'UTF-8',
        responseHeaders: '',
        responseBody: '',
        requestPath: {
            path: '',
            isAutoGenerated: true
        },
        requestHeaders: '',
        requestBody: ''
    },
    proxy: {
        rootProperty: 'entries',
        pagination: false,
        api: {
            findOne: {
                url: '/mock',
                method: 'get',
                responseProperty: 'entries'
            },
            update: {
                url: '/update',
                method: 'post',
                responseProperty: 'entries'
            },
            read: {
                url: '/read',
                method: 'get',
                responseProperty: 'entries'
            },
            destroy: {
                url: '/destroy',
                method: 'post',
                responseProperty: 'entries'
            },
            search: {
                url: '/search',
                method: 'post',
                responseProperty: 'entries'
            }
        }
    }
});
